VIA_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

EXTRAKEY_ENABLE = yes

MOUSEKEY_ENABLE = yes
QMK_SETTINGS = yes


POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

SRC += drivers/sensors/pmw3360.c


DYNAMIC_KEYMAP_LAYER_COUNT = 5